apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- target:            
    kind: HostedCluster
    name: template
  patch: |-                   
    - op: replace
      path: /metadata/name
      value: hcp01
bases:
- ../base