apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- patch: |-                   ## ClusterName
  - op: replace
    path: /metadata/name
    value: hcp01
  target:
    kind: HostedCluster
    name: template
- patch: |-                   ## ClusterNetworkCIDR
  - op: replace
    path: /spec/networking/clusterNetwork
    value: 10.136.0.0/14
  target:
    kind: HostedCluster
    name: template
bases:
- ../base