apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- target: ## ClusterName
    kind: HostedCluster
    name: template
  patch: |-                   
    - op: replace
      path: /metadata/name
      value: hcp02

- target: ## ClusterNetworkCIDR
    kind: HostedCluster
    name: template
  patch: |-                   
    - op: replace
      path: /spec/networking/clusterNetwork
      value: 10.137.0.0/14

- target: ## serviceNetworkCIDR
    kind: HostedCluster
    name: template
  patch: |-                   
    - op: replace
      path: /spec/networking/serviceNetwork
      value: 172.32.0.0/16

- target: ## InfraID
    kind: HostedCluster
    name: template
  patch: |-                   
    - op: replace
      path: /spec/infraID
      value: hcp02

- target: ## NodePool name
    kind: NodePool
    name: template
  patch: |-                   
    - op: replace
      path: /metadata/name
      value: hcp02

- target: ## Assosiated cluster name
    kind: NodePool
    name: template
  patch: |-                   
    - op: replace
      path: /spec/clusterName
      value: hcp02

- target: ## Number of worker
    kind: NodePool
    name: template
  patch: |-                   
    - op: replace
      path: /spec/replicas
      value: 2 

- target: ## Number of core by worker
    kind: NodePool
    name: template
  patch: |-                   
    - op: replace
      path: /spec/platform/kubevirt/compute/cores
      value: 4

- target: ## Number of MEM by worker
    kind: NodePool
    name: template
  patch: |-                   
    - op: replace
      path: /spec/platform/kubevirt/compute/memory
      value: 12 

bases:
- ../base