apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  name: template
  namespace: clusters
  labels:
    "cluster.open-cluster-management.io/clusterset": 'managed-clusters'
spec:
  etcd:
    managed:
      storage:
        persistentVolume:
          size: 8Gi
          storageClassName: ocs-storagecluster-ceph-rbd
        type: PersistentVolume
    managementType: Managed
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.19.17-multi
  pullSecret:
    name: pullsecret-cluster-hcp01
  sshKey:
    name: sshkey-cluster-hcp01
  networking:
    clusterNetwork:
      - cidr: 10.132.0.0/14
    serviceNetwork:
      - cidr: 172.31.0.0/16
    networkType: OVNKubernetes
  controllerAvailabilityPolicy: HighlyAvailable
  infrastructureAvailabilityPolicy: HighlyAvailable
  platform:
    type: KubeVirt
    kubevirt:
      baseDomainPassthrough: true
      storageDriver:
        type: Manual
        manual:
          storageClassMapping:
            - infraStorageClassName: ocs-storagecluster-ceph-rbd
              guestStorageClassName: ocp-virt-rbd
  infraID: 'template'
  services:
    - service: OAuthServer
      servicePublishingStrategy:
        type: Route
    - service: OIDC
      servicePublishingStrategy:
        type: Route
    - service: Konnectivity
      servicePublishingStrategy:
        type: Route
    - service: Ignition
      servicePublishingStrategy:
        type: Route