apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:

- target: ## NameSpace Creation
    kind: Namespace
    name: template
  patch: |-                   
    - op: replace
      path: /metadata/name
      value: hcp04

- target: ## ClusterName
    kind: HostedCluster
    name: template
  patch: |-                   
    - op: replace
      path: /metadata/name
      value: hcp04

- target: ## OCP Version
    kind: HostedCluster
    name: template
  patch: |-                   
    - op: replace
      path: /spec/release/image
      value: quay.io/openshift-release-dev/ocp-release:4.19.17-multi

- target: ## ClusterNetworkCIDR
    kind: HostedCluster
    name: template
  patch: |-                   
    - op: replace
      path: /spec/networking/clusterNetwork/0
      value: 
        cidr: 10.134.0.0/14

- target: ## serviceNetworkCIDR
    kind: HostedCluster
    name: template
  patch: |-                   
    - op: replace
      path: /spec/networking/serviceNetwork/0
      value: 
        cidr: 172.33.0.0/16

- target: ## InfraID
    kind: HostedCluster
    name: template
  patch: |-                   
    - op: replace
      path: /spec/infraID
      value: hcp04

- target: ## NodePool name
    kind: NodePool
    name: template
  patch: |-                   
    - op: replace
      path: /metadata/name
      value: hcp04

- target: ## Assosiated cluster name
    kind: NodePool
    name: template
  patch: |-                   
    - op: replace
      path: /spec/clusterName
      value: hcp04

- target: ## Number of worker
    kind: NodePool
    name: template
  patch: |-                   
    - op: replace
      path: /spec/replicas
      value: 3

- target: ## Number of core by worker
    kind: NodePool
    name: template
  patch: |-                   
    - op: replace
      path: /spec/platform/kubevirt/compute/cores
      value: 4

- target: ## Number of MEM by worker
    kind: NodePool
    name: template
  patch: |-                   
    - op: replace
      path: /spec/platform/kubevirt/compute/memory
      value: 20Gi

- target: ## OCP Release
    kind: NodePool
    name: template
  patch: |-                   
    - op: replace
      path: /spec/release/image
      value: quay.io/openshift-release-dev/ocp-release:4.19.17-multi

- target: ## ManagedCluster lablel
    kind: ManagedCluster
  patch: |-                   
    - op: replace
      path: /metadata/labels/name
      value: hcp04

- target: ## ManagedCluster lablel
    kind: ManagedCluster
  patch: |-                   
    - op: replace
      path: /metadata/labels/env
      value: prod

- target: ## ManagedCluster lablel
    kind: ManagedCluster
  patch: |-                   
    - op: replace
      path: /metadata/name
      value: hcp04

- target: ## KlusterletAddonConfig name
    kind: KlusterletAddonConfig
  patch: |-                   
    - op: replace
      path: /metadata/name
      value: hcp04

- target: ## KlusterletAddonConfig name
    kind: KlusterletAddonConfig
  patch: |-                   
    - op: replace
      path: /metadata/namespace
      value: hcp04

- target: ## KlusterletAddonConfig name
    kind: KlusterletAddonConfig
  patch: |-                   
    - op: replace
      path: /spec/clusterName
      value: hcp04

- target: ## KlusterletAddonConfig name
    kind: KlusterletAddonConfig
  patch: |-                   
    - op: replace
      path: /spec/clusterNamespace
      value: hcp04

bases:
- ../base