apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-dns
  namespace: clusters
data:
  config: |
    apiVersion: machineconfiguration.openshift.io/v1
    kind: MachineConfig
    metadata:
      name: 99-worker-dns
      labels:
        machineconfiguration.openshift.io/role: worker
    spec:
      config:
        ignition:
          version: 3.2.0
        storage:
          files:
            - path: /etc/NetworkManager/conf.d/dns-servers.conf
              mode: 0644
              contents:
                source: data:text/plain;charset=utf-8;base64,I2ZvcmNlIGRucwpkb21haW49ZXhhbXBsZS5jb20KbmFtZXNlcnZlcj0xMC42LjE4Ni41IDEwLjExLjAuMTQgMTAuMTEuMC4xMw==

