apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-dns
  namespace: clusters
data:
  config: |
    apiVersion: machineconfiguration.openshift.io/v1
    kind: MachineConfig
    metadata:
      name: custom-dns
    spec:
      config:
        ignition:
          version: 3.2.0
        storage:
          files:
            - path: /etc/NetworkManager/conf.d/custom-dns.conf
              mode: 0644
              contents:
                source: data:text/plain;charset=utf-8;base64,W21haW5dCmRucz1ub25lCgpbZ2xvYmFsLWRucy1kb21haW4tKl0KbmFtZXNlcnZlcnM9MTAuNi4xODYuNSwxMC4xMS4wLjE0LDEwLjExLjAuMTM=
